### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by JulienRe** [Kittikornl/monitor-trade#1]
Hello,

What Python version are you using please ? Thank you

**Comment by JulienRe** [comment]
Because I have this error :

`cute python script
You can also enter a command to execute (e.g /path/to/manage.py migrate). Note, only python scripts allowed.
main.py
Run Script
returncode: 1
stdout:

stderr:
Traceback (most recent call last):
  File "/main.py", line 3, in <module>
    from utils import *
  File "/utils.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests`

**Comment by Kittikornl** [comment]
It is 3.8.11
